### ISSUE TITLE
lowercase_constants: Enable configuration.

### ISSUE THREAD

**Issue by drupol** [FriendsOfPHP/PHP-CS-Fixer#4274]
This issue is to have the `lowercase_constants` directive configurable. (Issue #3026)
The configurable option would let you choose in between 'upper' or 'lower' case syntax.

Here's an example on how it would be:

```yaml
lowercase_constants:
   syntax: upper
```
or
```yaml
lowercase_constants:
   syntax: lower
```

The default would be `lower` to be backward compatible.

Why this request ?
CMS's like Drupal 8 are using uppercase constants (TRUE, FALSE, NULL) and I would like to have a proper tool that follows the Drupal 8 "standard" in our custom code at European Commission.

#### The PHP version you are using (`$ php -v`):
=> PHP 7.2.14

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
=> PHP CS Fixer 2.14.1-DEV Sunrise by Fabien Potencier and Dariusz Ruminski

#### The command you use to run PHP CS Fixer:
=> Via grumphp

#### The configuration file you are using, if any:
```yaml
        array_syntax:
            syntax: short
        blank_line_after_opening_tag: true
        blank_line_before_statement:
            statements:
                - break
                - continue
                - declare
                - return
                - throw
                - try
        include: true
        # Drupalism:
        class_attributes_separation: false
        declare_equal_normalize:
            space: single
        declare_strict_types: true
        is_null: true
        lowercase_static_reference: true
        # Drupalism: lowercase_constants (unable to configure it in php-cs-fixer. Provide a patch?)
        native_function_invocation: false
        # Drupalism:
        no_blank_lines_after_class_opening: false
        no_closing_tag: true
        no_extra_blank_lines:
            tokens:
                - extra
                # Drupalism: - curly_brace_block
                - parenthesis_brace_block
                - square_brace_block
                - return
                - throw
                - use
                - use_trait
        no_trailing_whitespace_in_comment: true
        no_unneeded_final_method: true
        single_blank_line_at_eof: true
        single_line_after_imports: true
        strict_comparison: true
        strict_param: true
        trailing_comma_in_multiline_array: true
        yoda_style:
            equal: false
            identical: false
            less_and_greater: false
            always_move_variable: false
```

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
if ($var === null) {
  // Do something
}
```

 * with unexpected changes applied when running PHP CS Fixer:
```php
if ($var === null) {
  // Do something
}
```

 * with the changes you expected instead:
```php
if ($var === NULL) {
  // Do something
}
```
