### ISSUE TITLE
GithubAction: use php-cs-fixer cache

### ISSUE THREAD

**Issue by staabm** [FriendsOfPHP/PHP-CS-Fixer#4938]
hey guys,

when using the latest php-cs-fixer on a github-action build, I want to utilize caching. 

that should be similar to composer dependencies caching which can be achieved with 
```yaml
    - name: Get composer cache directory
      id: composer-cache
      run: echo "::set-output name=dir::$(composer config cache-files-dir)"

    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-
```

see https://github.com/actions/cache/blob/master/examples.md

will it work, if I add github-action caching for the `.php_cs.cache` file, or might the cs-fixer get confused by the file beeing present? which variables should be used for the cache-key?

thanks for your ideas/input in advance

**Comment by staabm** [comment]
we might have to work arround some limitations, because it is documented that you cannot cache a single file

https://help.github.com/en/actions/configuring-and-managing-workflows/caching-dependencies-to-speed-up-workflows#input-parameters-for-the-cache-action

**Comment by julienfalque** [comment]
Using PHP CS Fixer's cache feature requires accurate files modification times which is rarely the case on CI systems because they create a new copy of the source for each job, having modification times always greater than what was stored in `.php_cs.cache`. Not sure about Github Action though as I never played with it yet.

An alternative solution is to [explicitly pass the files that changed as arguments to PHP CS Fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer#using-php-cs-fixer-on-ci). Also maybe we can make the cache system smarter by e.g. comparing file checksums in addition to modification times?

**Comment by staabm** [comment]
> Using PHP CS Fixer's cache feature requires accurate files modification times which is rarely the case on CI systems because they create a new copy of the source for each job, having modification times always greater than what was stored in `.php_cs.cache`.

ahh this might be the reason why phpstan uses a md5 based hashing instead of file-modification times for its cache feature. thanks for the insights.

phpstan seems to use 1 cache file per 1 source file.. that way it can re-use the cache across different builds (even the builds of different branches can re-use stuff from e.g. builds running on the master branch). it doesnt use a single cache file for everything and re-builds it entirely when only a few files change

**Comment by staabm** [comment]
> maybe we can make the cache system smarter by e.g. comparing file checksums in addition to modification times?

I did some investigations and as far as I can tell, the cache is already based on checksums, not on modification times:

https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/src/Cache/FileCacheManager.php

**Comment by staabm** [comment]
I did some tests and came to the following examples (which works \o/):

https://github.com/clxmstaab/PHP-CS-Fixer/blob/ed202482e4c0e5691bf8453c5cfc20a13f84349a/.github/workflows/caching.yml#L30-L60

important points:
- the actions/cache@1 GitHubAction only works with directories
- we need to define a separate directory, e.g. within /tmp/ create it and put the cache file in there.
- it does not work to put the cache file directly into /tmp and cache/restore the /tmp folder

**Comment by bendavies** [comment]
we are doing this.
you can either key on the commit.sha so you get an addative cache
```php
$config->setCacheFile(__DIR__.'/.build/php-cs-fixer/.php_cs.cache');
```

```yaml
      - name: "Cache cache directory for friendsofphp/php-cs-fixer"
        uses: actions/cache@v1
        with:
          path: .build/php-cs-fixer
          key: php-${{ matrix.php-version }}-php-cs-fixer-${{ github.sha }}
          restore-keys: php-${{ matrix.php-version }}-php-cs-fixer-

      - name: "Run friendsofphp/php-cs-fixer"
        run: vendor/bin/php-cs-fixer fix --diff --diff-format=udiff --dry-run --verbose
```

or if you don't like that, you could create your own key based on a manually calculated cache key with something like
```sh
find src tests -type f -name "*.php" -exec md5sum {} + > php-cs-fixer.checksum
```

```yaml
      - name: "Cache cache directory for friendsofphp/php-cs-fixer"
        uses: actions/cache@v1
        with:
          path: .build/php-cs-fixer
          key: php-${{ matrix.php-version }}-php-cs-fixer-${{ hashFiles('php-cs-fixer.checksum') }}
          restore-keys: php-${{ matrix.php-version }}-php-cs-fixer-
```

**Comment by staabm** [comment]
@bendavies thx for your suggestions.
Both do not make sense to me though.

> you can either key on the commit.sha so you get an additive cache

This would only work when the same commit would be bouilt over and over again. I dont think this is a common use-case in CI

> or if you don't like that, you could create your own key based on a manually calculated cache key with something like

This does not make sense to me either. The builtin caching mechanics of php-cs-fixer already keep track of this conditions, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/f385e1b93988e72445a7585a1acceacea2b39d2e/src/Cache/FileCacheManager.php#L20-L25

**Comment by bendavies** [comment]
hi @staabm .

First, you need to understand that there is a peculiarity with `actions/cache`: it will not update a cache item if the key does not change. This can be clearly seen in your workflow run here:
https://github.com/clxmstaab/PHP-CS-Fixer/runs/653574779?check_suite_focus=true
<img width="586" alt="image" src="https://user-images.githubusercontent.com/625392/81334460-fd2be900-909d-11ea-8db0-9af1b820dd88.png">

Hopefully you now see why your workflow does not work. your Cache will never update, even if php files update, since your cache key is hard coded to `${{ runner.os }}-fixer-2`. So even if you update php files, you'll be left with a stale cache, which will get more and more stale over time.

Now:

> Maybe I am missing something?

Yes, you are missing the usage of the fall back to `restore-keys`.

Taking this example, 
```yaml
      - name: "Cache cache directory for friendsofphp/php-cs-fixer"
        uses: actions/cache@v1
        with:
          path: .build/php-cs-fixer
          key: php-${{ matrix.php-version }}-php-cs-fixer-${{ github.sha }}
          restore-keys: php-${{ matrix.php-version }}-php-cs-fixer-
```
The following will happen.

1. dev commits commit `aaaaaaaa`
1. Cache misses for key `php-7.4-php-cs-fixer-aaaaaaaa`
1. Cache misses for key`php-7.4-php-cs-fixer`
1. php-cs-fixer runs.
1. Cache is saved with key `php-7.4-php-cs-fixer-aaaaaaaa`
1. dev commits commit `bbbbbbbb`
1. Cache misses for key `php-7.4-php-cs-fixer-aaaaaaaa`
1. Cache HITS for key`php-7.4-php-cs-fixer` (which is actually `php-7.4-php-cs-fixer-aaaaaaaa` saved in the previous run)
1. php-cs-fixer runs with a fully primed cache, very fast, only fixing updating changed php files in commit `bbbbbbbb`
1. Cache is saved with key `php-7.4-php-cs-fixer-bbbbbbbb`
1. dev commits commit `ccccccc`
1. etc...

There are other semantics of the `restore-key` fallbacks related to branches which you can read [here](https://help.github.com/en/actions/configuring-and-managing-workflows/caching-dependencies-to-speed-up-workflows#using-the-cache-action).

The upshot that if you want a cache to be updated, you need to use a changing cache key. `${{ github.sha }}` achieves that nicely.
You only need to do this however when you don't have some asset to hash, e.g. we use `${{ hashFiles('composer.lock') }}` for composer dep caching.

I hope that helps.

**Comment by julienfalque** [comment]
> the cache is already based on checksums

Damn, not sure why I thought it was based on timestamps only 😆️

**Comment by localheinz** [comment]
@staabm 

This works well for me:

- https://github.com/ergebnis/php-library-template/blob/d97e45ff409fb7e591dda96cb2cd771e901552d2/.php_cs#L41

    ```php
    $config->setCacheFile(__DIR__ . '/.build/php-cs-fixer/.php_cs.cache');
    ```

- https://github.com/ergebnis/php-library-template/blob/d97e45ff409fb7e591dda96cb2cd771e901552d2/.github/workflows/integrate.yaml#L77-L88

    ```yaml
          - name: "Create cache directory for friendsofphp/php-cs-fixer"
            run: "mkdir -p .build/php-cs-fixer"

          - name: "Cache cache directory for friendsofphp/php-cs-fixer"
            uses: "actions/cache@v2.0.0"
            with:
              path: ".build/php-cs-fixer"
              key: "php-${{ matrix.php-version }}-php-cs-fixer-${{ hashFiles('composer.lock') }}"
              restore-keys: "php-${{ matrix.php-version }}-php-cs-fixer-"

          - name: "Run friendsofphp/php-cs-fixer"
            run: "vendor/bin/php-cs-fixer fix --config=.php_cs --diff --diff-format=udiff --dry-run --verbose"
    ```
