### ISSUE TITLE
release cycle on phar synced with master or tagged version

### ISSUE THREAD

**Issue by cordoval** [FriendsOfPHP/PHP-CS-Fixer#519]
I use bldr and run ./dev cs and it downloads the phar but i am seeing it is not the latest, is very behind maybe?

``` yaml
        runFixer:
            description: Installs if not already and runs php-cs-fixer with custom .php_cs
            calls:
                -
                    type: exec
                    executable: curl
                    arguments:
                        - http://cs.sensiolabs.org/get/php-cs-fixer.phar
                        - -S
                        - -o
                        - php-cs-fixer.phar
                -
                    type: exec
                    executable: php
                    arguments:
                        - php-cs-fixer.phar
                        - fix
                        - --config=.php_cs

```

I see https://redbot.org/?uri=http%3A%2F%2Fget.sensiolabs.org%2Fphp-cs-fixer.phar

but still i think something is messed up

``` bash
  [RuntimeException]
  Not enough arguments.



fix [--config="..."] [--dry-run] [--level="..."] [--fixers="..."] [--diff] [--format="..."] path





  [Exception]
  Failed on the runFixer task.

    [RuntimeException]
    Not enough arguments.

  fix [--config="..."] [--dry-run] [--level="..."] [--fixers="..."] [--diff] [--format="..."] path
```

notice the --config rather than --config-file

i run with a clone and it works as expected, but the phar is messed up somehow.
