### ISSUE TITLE
Alternative path-mode for CI

### ISSUE THREAD

**Issue by ro0NL** [FriendsOfPHP/PHP-CS-Fixer#5948]
Hi,

We currently run PHP-CS-Fixer on our CI. Since our codebase isnt fully updated yet, we only dry-run fix "added files" without any cache to ensure new files are conform CS.

However, if eg. some XML file is added in a PR .. the CI turns red because we pass this file to PHP-CS-Fixer.

I assume running PHP-CS-Fixer without path arguments but with cache is a long way for us, however red CI is not an option :)

As such, WDYT about a new path mode that only fixes passed files that are a subset of the configured files (as we do pass a config parameter).

**Comment by ro0NL** [comment]
Basically this is happening:

```yaml
    php-cs-fixer:
        runs-on: ubuntu-latest
        needs: [ php-lint ]
        steps:
            -   uses: actions/checkout@v2
                with:
                    fetch-depth: 2

            -   uses: tj-actions/changed-files@v9
                id: changed-files

            -   if: ${{ steps.changed-files.outputs.added_files }} # all_modified_files
                uses: docker://oskarstark/php-cs-fixer-ga
                with:
                    args: --config=.php-cs-fixer.php --ansi --diff --dry-run --using-cache=no "${{ steps.changed-files.outputs.added_files }}" # all_modified_files
```
