### ISSUE TITLE
Ruined CSS, if CSS contain PHP inside

### ISSUE THREAD

**Issue by geost77** [FriendsOfPHP/PHP-CS-Fixer#6261]
I have CSS like this:

```css
.element_<?=$id?>_blue { color: blue }
```

It become:

```css
.element_

<?=$id?>
_blue {
     color: blue
}
```

Obviously ruin my CSS selector splitting it this way. No such issue if that is HTML, only happen inside CSS.
